include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

linter:
  rules:
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    omit_local_variable_types: false
    curly_braces_in_flow_control_structures: true
    sort_constructors_first: true
    prefer_final_locals: true
    annotate_overrides: true
    unnecessary_this: true
